# -*- coding: utf-8 -*-
"""infosys_Project(Model2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zEewg9l53ZWuPESUpfNPISBw9QssHx_b
"""

import pandas as pd
import numpy as np

blood_report = {
    "Hemoglobin": 11.2,          # g/dL
    "Glucose": 142,              # mg/dL
    "Total_Cholesterol": 240,    # mg/dL
    "LDL": 160,                  # mg/dL
    "HDL": 35,                   # mg/dL
    "Triglycerides": 210,        # mg/dL
    "Creatinine": 1.4            # mg/dL
}

print("Input Blood Report:")
blood_report

df = pd.DataFrame([blood_report])
df

def detect_medical_patterns(data):
    patterns = []

    # Cardiovascular Risk (Dyslipidemia)
    if data["LDL"] > 130 and data["HDL"] < 40:
        patterns.append("High Cardiovascular Risk (Dyslipidemia)")

    # Diabetes Risk
    if data["Glucose"] >= 126:
        patterns.append("Diabetes Risk")

    # Metabolic Syndrome Risk
    if (data["Glucose"] >= 110 and
        data["Triglycerides"] >= 150 and
        data["HDL"] < 40):
        patterns.append("Metabolic Syndrome Risk")

    # Kidney Function Risk
    if data["Creatinine"] > 1.3:
        patterns.append("Possible Kidney Function Impairment")

    # Anemia Risk
    if data["Hemoglobin"] < 12:
        patterns.append("Anemia Risk")

    return patterns

def calculate_cardiovascular_risk(data):
    ldl_hdl_ratio = data["LDL"] / data["HDL"]
    tg_factor = data["Triglycerides"] / 150

    risk_score = ldl_hdl_ratio + tg_factor

    if risk_score < 5:
        risk_level = "Low"
    elif risk_score < 7:
        risk_level = "Moderate"
    else:
        risk_level = "High"

    return round(risk_score, 2), risk_level

patterns_detected = detect_medical_patterns(blood_report)
cv_score, cv_risk = calculate_cardiovascular_risk(blood_report)

model_2_output = {
    "Detected_Patterns": patterns_detected,
    "Cardiovascular_Risk_Score": cv_score,
    "Cardiovascular_Risk_Level": cv_risk
}

print("MODEL 2 OUTPUT:")
model_2_output

print("Model 2 Summary ")

if patterns_detected:
    print("Identified Health Patterns:")
    for p in patterns_detected:
        print("-", p)
else:
    print("No significant patterns detected.")

print("\nCardiovascular Risk Score:", cv_score)
print("Cardiovascular Risk Level:", cv_risk)

