# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Pk3JP9jpEcfTa6nRyUydZWq2jzibTmy
"""

!apt-get install tesseract-ocr -y
!pip install pytesseract
!pip install pdfplumber

# imports
import os
import pytesseract
from PIL import Image
import pdfplumber
import re

# File Type
def detect_file_type(file_path):
    ext = os.path.splitext(file_path)[1].lower()
    if ext in ['.pdf']:
        return 'pdf'
    elif ext in ['.png', '.jpg', '.jpeg']:
        return 'image'
    elif ext in ['.json']:
        return 'json'
    else:
        return 'unsupported'

# Extract text from pdf
def extract_from_pdf(path):
    text = ""
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            text += page.extract_text() + "\n"
    return text

# Extract text From image
def extract_from_image(path):
    img = Image.open(path)
    text = pytesseract.image_to_string(img)
    return text

# Unified Data Exicution
def extract_data(file_path):
    file_type = detect_file_type(file_path)
    if file_type == 'pdf':
        return extract_from_pdf(file_path)
    elif file_type == 'image':
        return extract_from_image(file_path)
    else:
        raise ValueError("Unsupported file format")

# Function for Parameter
def extract_parameters(text):
    params = {}
    hb = re.search(r'Hemoglobin\s*[:\-]?\s*(\d+\.?\d*)', text, re.I)
    glucose = re.search(r'Glucose\s*[:\-]?\s*(\d+\.?\d*)', text, re.I)
    if hb:
        params['Hemoglobin'] = float(hb.group(1))
    if glucose:
        params['Glucose'] = float(glucose.group(1))
    return params

# Defining Normal range
NORMAL_RANGES = {
    "Hemoglobin": (13.0, 17.0),
    "Glucose": (70, 100)
}

def interpret_parameters(params):
    result = {}
    for key, value in params.items():
        low, high = NORMAL_RANGES.get(key, (None, None))
        if low is None:
            result[key] = "Range not defined"
        elif value < low:
            result[key] = "Low"
        elif value > high:
            result[key] = "High"
        else:
            result[key] = "Normal"
    return result

# file path
file_path = '/content/33806e7015fbfcaff211.png'
text = extract_data(file_path)
params = extract_parameters(text)
interpretation = interpret_parameters(params)

# Result part
print("Extracted Parameters:", params)
print("Interpretation:", interpretation)

