def generate_report(
    parameters: dict,
    interpretation: dict,
    risks: list,
    summary: str,
    recommendations: list
):
    """
    Generates a clean, user-friendly health report.
    """

    report = []

    report.append("AUTOMATED HEALTH DIAGNOSTIC REPORT")
    report.append("=" * 40)

    report.append("\n1. Extracted Blood Parameters:")
    for param, value in parameters.items():
        report.append(f"- {param}: {value}")

    report.append("\n2. Parameter Interpretation:")
    for param, status in interpretation.items():
        report.append(f"- {param}: {status}")

    report.append("\n3. Risk Assessment:")
    for risk in risks:
        report.append(f"- {risk}")

    report.append("\n4. Summary:")
    report.append(summary)

    report.append("\n5. Recommendations:")
    for rec in recommendations:
        report.append(f"- {rec}")

    report.append("\n" + "=" * 40)
    report.append(
        "IMPORTANT DISCLAIMER:\n"
        "This report is generated by an AI system for educational purposes only.\n"
        "It does NOT replace consultation with a qualified medical professional."
    )

    return "\n".join(report)
