import streamlit as st
from src.parser import parse_input
from src.extractor import extract_data
from src.validator import standardize_data
from src.interpreter import interpret_parameters
from src.agents.pattern_agent import pattern_recognition_agent
from src.agents.context_agent import contextual_analysis_agent

st.set_page_config(page_title="AI Health Agent", layout="wide")

# Sidebar for User Context (Milestone 2/3 requirement)
with st.sidebar:
    st.header("👤 User Profile")
    age = st.number_input("Age", min_value=1, max_value=120, value=30)
    gender = st.selectbox("Gender", ["Male", "Female", "Other"])
    goal = st.selectbox("Primary Goal", ["Fatigue Management", "Weight Loss", "Heart Health", "General Checkup"])
    history = st.text_area("Medical History", placeholder="e.g., Anemia history, Hypertension")

st.title("🩸 Intelligent Blood Report Diagnostic System")

uploaded_file = st.file_uploader("Upload Report (PDF/Image)", type=['pdf', 'png', 'jpg'])

if uploaded_file:
    user_context = {"age": age, "gender": gender, "goal": goal, "history": history}
    
    with st.spinner("Step 1: Extracting & Standardizing Data..."):
        raw_content, c_type = parse_input(uploaded_file)
        extracted = extract_data(raw_content)
        valid_data = standardize_data(extracted)
        # Model 1: Interpretation
        interpreted_data = interpret_parameters(valid_data)

    # UI Tabs for organized viewing
    tab1, tab2, tab3 = st.tabs(["📋 Extracted Data", "🧬 AI Analysis", "🥗 Health Plan"])

    with tab1:
        st.subheader("Clinical Data Summary")
        st.dataframe(interpreted_data, use_container_width=True)

    with tab2:
        st.subheader("Multi-Model Reasoning")
        col1, col2 = st.columns(2)
        
        with col1:
            st.info("Model 2: Pattern Recognition")
            patterns = pattern_recognition_agent(interpreted_data)
            for p in patterns:
                st.write(f"**{p['pattern']}**: {p['finding']}")
        
        with col2:
            st.success("Model 3: Contextual Analysis")
            context_insight = contextual_analysis_agent(interpreted_data, patterns, user_context)
            st.write(context_insight)

    with tab3:
        st.subheader("Personalized Recommendations")
        # Placeholder for Milestone 3 Synthesis Engine
        st.write(f"Based on your goal of **{goal}**, our AI suggests:")
        st.markdown("- Increase iron-rich foods if Hemoglobin is low.")
        st.markdown("- Schedule a follow-up consultation for High severity markers.")
        
        # Mandatory Medical Disclaimer (Milestone 4 requirement)
        st.warning("**Disclaimer:** This report is generated by an AI agent for educational purposes and is NOT a medical diagnosis. Consult a physician before making health changes.")
