from datetime import datetime
import streamlit as st
from src.parser import parse_input
from src.extractor import extract_data
from src.validator import standardize_data
from src.interpreter import interpret_parameters
from src.agents.pattern_agent import pattern_recognition_agent
from src.agents.context_agent import contextual_analysis_agent
from src.agents.recommendation_engine import recommendation_engine
from src.utils.guardrails import apply_guardrails
from src.utils.reporter import generate_pdf_report

st.set_page_config(page_title="AI Health Agent", layout="wide")

# Sidebar for User Context
with st.sidebar:
    st.header("User Profile")
    age = st.number_input("Age", min_value=1, max_value=120, value=30)
    gender = st.selectbox("Gender", ["Male", "Female", "Other"])
    goal = st.selectbox("Primary Goal", ["General Checkup", "Weight Loss", "Heart Health", "Fatigue Management"])
    history = st.text_area("Medical History", placeholder="e.g., Anemia history, Hypertension")

st.title("Intelligent Blood Report Diagnostic System")

uploaded_file = st.file_uploader("Upload Report (PDF/Image)", type=['pdf', 'png', 'jpg'])

if uploaded_file:
    user_context = {"age": age, "gender": gender, "goal": goal, "history": history}
    
    # --- DATA PROCESSING STEP ---
    # We do the analysis once here so all tabs have access to the data
    with st.spinner("Step 1: Extracting & Analyzing Data..."):
        raw_content, c_type = parse_input(uploaded_file)
        extracted = extract_data(raw_content)
        valid_data = standardize_data(extracted)
        interpreted_data = interpret_parameters(valid_data)
        
        # Agent Analysis
        patterns = pattern_recognition_agent(interpreted_data)
        patterns = pattern_recognition_agent(interpreted_data)

        # If only disclaimer pattern detected
        if len(patterns) == 1 and "No Significant Clinical Pattern" in patterns[0]["pattern"]:
            st.info("ℹ️ No major clinical abnormalities detected based on available data.")
        context_insight = contextual_analysis_agent(interpreted_data, patterns, user_context)
        
        # Synthesis & Guardrails
        full_analysis = f"Patterns: {patterns}\nContext: {context_insight}"
        raw_recs = recommendation_engine(full_analysis, user_context)
        safe_recs = apply_guardrails(raw_recs)
        
        # Final Report Generation
        pdf_file = generate_pdf_report(
            interpreted_data, 
            patterns,
            safe_recs, 
            user_context
        )

    # --- UI TABS ---
    tab1, tab2, tab3 = st.tabs(["📋 Extracted Data", "🧬 AI Analysis", "🥗 Health Plan"])

    with tab1:
        st.subheader("Clinical Data Summary")
        st.dataframe(interpreted_data, use_container_width=True)

    with tab2:
        st.subheader("Multi-Model Reasoning")
        col1, col2 = st.columns(2)
        
        with col1:
            st.info("Model 2: Pattern Recognition")
            for p in patterns:
                st.write(f"**{p.get('pattern', 'N/A')}**: {p.get('finding', 'N/A')}")
        
        with col2:
            st.success("Model 3: Contextual Analysis")
            st.write(context_insight)

    with tab3:
        st.subheader("🥗 Your Personalized Health Plan")
        st.markdown(safe_recs)
        
        st.divider()
        st.subheader("📄 Export Final Report")
        
        col_btn1, col_btn2 = st.columns(2)
        with col_btn1:
            st.download_button(
                label="Download Clinical Summary (PDF)",
                data=pdf_file,
                file_name=f"Health_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
                mime="application/pdf" # Ensure this matches your reporter output
            )

    # Mandatory Medical Disclaimer
    st.warning("**Disclaimer:** This report is generated by an AI agent for educational purposes and is NOT a medical diagnosis. Consult a physician before making health changes.")
