def generate_recommendations(patterns, model1_results, risk_score):
    """
    Generates patient-friendly, reassuring, and actionable health recommendations
    based on detected risk patterns and overall risk score.
    """

    recommendations = []

    # ---------- PATTERN-SPECIFIC GUIDANCE ----------
    for p in patterns:
        pattern = p["pattern"]

        if "Anemia" in pattern:
            recommendations.append(
                "Your blood report shows signs that may be related to low hemoglobin levels. "
                "This is quite common and often manageable. Including iron-rich foods such as "
                "green leafy vegetables, lentils, dates, jaggery, and nuts in your diet may help. "
                "If you feel tired, dizzy, or breathless, consider speaking with a doctor for further guidance."
            )

        if "Leukopenia" in pattern:
            recommendations.append(
                "A slightly low white blood cell count can sometimes make it easier to catch infections. "
                "Try to maintain good hygiene, wash hands regularly, and get adequate rest. "
                "If you notice frequent infections or fever, it is a good idea to consult a healthcare professional."
            )

        if "Thrombocytopenia" in pattern:
            recommendations.append(
                "Your platelet count appears to be on the lower side. Platelets help with blood clotting, "
                "so it is important to avoid unnecessary injuries. Refrain from taking painkillers "
                "like aspirin unless advised by a doctor, and seek medical advice if you notice unusual bruising or bleeding."
            )

        if "Thrombocytosis" in pattern:
            recommendations.append(
                "Your platelet count is higher than normal. This can happen for various reasons, including stress or inflammation. "
                "Staying well-hydrated and following up with your doctor for repeat testing may be helpful."
            )

    # ---------- OVERALL RISK GUIDANCE ----------
    if risk_score < 30:
        recommendations.append(
            "Overall, your health risk appears to be low. Continuing a balanced diet, staying active, "
            "and having regular health check-ups can help maintain good health."
        )
    elif risk_score < 60:
        recommendations.append(
            "Your overall health risk is moderate. This does not usually require urgent action, "
            "but monitoring your health and scheduling a routine medical check-up is recommended."
        )
    else:
        recommendations.append(
            "Your overall health risk is higher. While this does not mean something is seriously wrong, "
            "it would be wise to consult a healthcare professional for a detailed evaluation and personalized advice."
        )

    # ---------- FRIENDLY DISCLAIMER ----------
    recommendations.append(
        "Please note that this interpretation is generated by an AI-based system and is meant to support awareness. "
        "It should not replace advice from a qualified healthcare professional."
    )

    return recommendations
